#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

# Start commands for application
require Mojolicious::Commands;

$ENV{MOJO_APP_ROOT} = "$FindBin::Bin/../lib";
$ENV{MOJO_CONFIG_FILE} = "$FindBin::Bin/../config.yml";

if (defined $ARGV[0] and $ARGV[0] eq 'test') {
  $ENV{MOJO_MODE} = 'test';

  # Testing Email::Sender::Simple
  $ENV{EMAIL_SENDER_TRANSPORT} = 'Test';
}

Mojolicious::Commands->start_app('PhotoShare');
